version: '3.8'

services:
  # InfluxDB - краткосрочное хранение метрик
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - '8086:8086'
    volumes:
      - './influxdb/data:/var/lib/influxdb2'

  # VictoriaMetrics - долгосрочное хранение метрик
  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: victoriametrics
    restart: always
    user: '1000'
    ports:
      - '8428:8428'
    volumes:
      - './victoriametrics/data:/victoria-metrics-data'
    command:
      - "--retentionPeriod=5y"

  # Grafana - визуализация
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: always
    user: '1000'
    ports:
      - '3000:3000'
    volumes:
      - './grafana/data:/var/lib/grafana'
      - './grafana/grafana.ini:/etc/grafana/grafana.ini'
